name: electronic_accessories_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  all_sensors2: ^1.0.1
  analyzer: ^2.8.0
  animated_switch: ^0.0.1
  animated_theme_switcher: ^2.0.6
  animations: ^2.0.3
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.6.21
  badges: ^2.0.3
  build: ^2.3.0
  built_value_generator: ^8.3.3
  code_builder: ^4.1.0
  dio: ^4.0.6
  email_validator: ^2.1.16
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: 
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  flutter_toastr: ^1.0.3
  fluttertoast: ^8.0.9
  font_awesome: ^5.10.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  hexcolor: ^2.0.7
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  image_picker: ^0.8.5+3
  ionicons: ^0.1.2
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  latlong2: ^0.8.1
  line_awesome_flutter: ^2.0.0
  local_image_provider: ^4.2.0
  mime: ^1.0.2
  motion_toast: ^2.1.6
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  sqflite: ^2.0.2+1
  string_validator: ^0.3.0
  url_launcher: ^6.1.2
  wear: ^1.1.0
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2

dev_dependencies:
 build_runner: ^2.1.11
 flutter_lints: ^2.0.1
 flutter_test:
    sdk: flutter
 integration_test:
    sdk: flutter
 floor_generator: ^1.2.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
   # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages



# Resolving dependencies... (15.7s)
#  _fe_analyzer_shared 31.0.0 (67.0.0 available)
#  analyzer 2.8.0 (6.4.1 available)
#  animated_switch 0.0.1 (0.0.3 available)
#  animated_theme_switcher 2.0.6 (2.0.10 available)
#  animations 2.0.3 (2.0.11 available)
#> archive 3.3.2 (was 3.3.0) (3.4.10 available)
#  args 2.3.1 (2.5.0 available)
#> async 2.10.0 (was 2.9.0) (2.11.0 available)
#  awesome_notifications 0.6.21 (0.9.3+1 available)
#  badges 2.0.3 (3.1.2 available)
#> boolean_selector 2.1.1 (was 2.1.0)
#  build 2.3.0 (2.4.1 available)
#  build_config 1.0.0 (1.1.1 available)
#  build_daemon 3.1.0 (4.0.1 available)
#  build_resolvers 2.0.6 (2.4.2 available)
#  build_runner 2.1.11 (2.4.9 available)
#  build_runner_core 7.2.3 (7.3.0 available)
#  built_value 8.3.2 (8.9.2 available)
#  built_value_generator 8.3.3 (8.9.2 available)
#  characters 1.2.1 (1.3.0 available)
#  checked_yaml 2.0.1 (2.0.3 available)
#  cli_util 0.3.5 (0.4.1 available)
#  code_builder 4.1.0 (4.10.0 available)
#> collection 1.17.0 (was 1.16.0) (1.18.0 available)
#  convert 3.0.1 (3.1.1 available)
#  cross_file 0.3.3+1 (0.3.4+1 available)
#  crypto 3.0.2 (3.0.3 available)
#  dart_style 2.2.1 (2.3.6 available)
#  dio 4.0.6 (5.4.3+1 available)
#  email_validator 2.1.16 (2.1.17 available)
#  ffi 1.2.1 (2.1.2 available)
#> file 6.1.4 (was 6.1.2) (7.0.0 available)
#  fixnum 1.0.1 (1.1.0 available)
#  floor 1.2.0 (1.4.2 available)
#  floor_annotation 1.0.1 (1.4.2 available)
#  floor_generator 1.2.0 (1.4.2 available)
#  flutter_lints 2.0.1 (3.0.2 available)
#  flutter_map 3.1.0 (6.1.0 available)
#  flutter_plugin_android_lifecycle 2.0.6 (2.0.19 available)
#  flutter_screenutil 5.5.3+2 (5.9.0 available)
#  flutter_svg 1.1.0 (2.0.10+1 available)
#  fluttertoast 8.0.9 (8.2.5 available)
#  frontend_server_client 2.1.3 (4.0.0 available)
#  get 4.6.5 (4.6.6 available)
#  glob 2.0.2 (2.1.2 available)
#  google_fonts 3.0.1 (6.2.1 available)
#  graphs 2.1.0 (2.3.1 available)
#  hexcolor 2.0.7 (3.0.1 available)
#  hive_generator 1.1.3 (2.0.1 available)
#  http 0.13.5 (1.2.1 available)
#  http_multi_server 3.2.0 (3.2.1 available)
#  http_parser 4.0.1 (4.0.2 available)
#  image_picker 0.8.5+3 (1.1.0 available)
#  image_picker_android 0.8.5+1 (0.8.10 available)
#  image_picker_for_web 2.1.8 (3.0.4 available)
#  image_picker_ios 0.8.5+5 (0.8.10 available)
#  image_picker_platform_interface 2.5.0 (2.10.0 available)
#  intl 0.17.0 (0.19.0 available)
#  io 1.0.3 (1.0.4 available)
#  ionicons 0.1.2 (0.2.2 available)
#> js 0.6.5 (was 0.6.4) (0.7.1 available)
#  json_annotation 4.5.0 (4.8.1 available)
#  json_serializable 6.2.0 (6.7.1 available)
#  latlong2 0.8.1 (0.9.1 available)
#  lints 2.0.0 (3.0.0 available)
#  local_image_provider 4.2.0 (4.3.0 available)
#  logging 1.0.2 (1.2.0 available)
#> matcher 0.12.13 (was 0.12.12) (0.12.16+1 available)
#> material_color_utilities 0.2.0 (was 0.1.5) (0.11.1 available)
#  meta 1.8.0 (1.14.0 available)
#  mime 1.0.2 (1.0.5 available)
#  motion_toast 2.1.8 (2.9.1 available)
#  package_config 2.0.2 (2.1.0 available)
#  path 1.8.2 (1.9.0 available)
#  path_drawing 1.0.0 (1.0.1 available)
#  path_parsing 1.0.0 (1.0.1 available)
#  path_provider 2.0.11 (2.1.3 available)
#  path_provider_android 2.0.16 (2.2.4 available)
#  path_provider_ios 2.0.10 (2.0.11 available)
#  path_provider_linux 2.1.7 (2.2.1 available)
#  path_provider_macos 2.0.6 (2.0.7 available)
#  path_provider_platform_interface 2.0.4 (2.1.2 available)
#  path_provider_windows 2.0.7 (2.2.1 available)
#  petitparser 5.0.0 (6.0.2 available)
#  platform 3.1.0 (3.1.4 available)
#  plugin_platform_interface 2.1.2 (2.1.8 available)
#  pool 1.5.0 (1.5.1 available)
#  process 4.2.4 (5.0.2 available)
#  provider 6.0.3 (6.1.2 available)
#  pub_semver 2.1.1 (2.1.4 available)
#  pubspec_parse 1.2.0 (1.2.3 available)
#  quiver 3.1.0 (3.2.1 available)
#  shared_preferences 2.0.15 (2.2.3 available)
#  shared_preferences_android 2.0.12 (2.2.2 available)
#  shared_preferences_linux 2.1.1 (2.3.2 available)
#  shared_preferences_macos 2.0.4 (2.0.5 available)
#  shared_preferences_platform_interface 2.0.0 (2.3.2 available)
#  shared_preferences_web 2.0.4 (2.3.0 available)
#  shared_preferences_windows 2.1.1 (2.3.2 available)
#  shelf 1.3.0 (1.4.1 available)
#  shelf_web_socket 1.0.1 (1.0.4 available)
#  source_gen 1.2.2 (1.5.0 available)
#  source_helper 1.3.2 (1.3.4 available)
#> source_span 1.9.1 (was 1.9.0) (1.10.0 available)
#  sqflite 2.0.2+1 (2.3.3 available)
#  sqflite_common 2.2.1+1 (2.5.4 available)
#  sqflite_common_ffi 2.1.1 (2.3.3 available)
#  sqlite3 1.7.1 (2.4.2 available)
#> stack_trace 1.11.0 (was 1.10.0) (1.11.1 available)
#> stream_channel 2.1.1 (was 2.1.0) (2.1.2 available)
#  stream_transform 2.0.0 (2.1.0 available)
#> string_scanner 1.2.0 (was 1.1.1)
#  string_validator 0.3.0 (1.0.2 available)
#  strings 0.2.2 (3.1.1 available)
#  synchronized 3.0.0+2 (3.1.0+1 available)
#> test_api 0.4.16 (was 0.4.12) (0.7.1 available)
#  timing 1.0.0 (1.0.1 available)
#  tuple 2.0.1 (2.0.2 available)
#  typed_data 1.3.1 (1.3.2 available)
#  url_launcher 6.1.2 (6.2.6 available)
#  url_launcher_android 6.0.17 (6.3.1 available)
#  url_launcher_ios 6.0.17 (6.2.5 available)
#  url_launcher_linux 3.0.1 (3.1.1 available)
#  url_launcher_macos 3.0.1 (3.1.0 available)
#  url_launcher_platform_interface 2.0.5 (2.3.2 available)
#  url_launcher_web 2.0.11 (2.3.1 available)
#  url_launcher_windows 3.0.1 (3.1.1 available)
#> vector_math 2.1.4 (was 2.1.2)
#> vm_service 9.4.0 (was 9.0.0) (14.2.1 available)
#  watcher 1.0.1 (1.1.0 available)
#  web_socket_channel 2.2.0 (2.4.5 available)
#> webdriver 3.0.1 (was 3.0.0) (3.0.3 available)
#  win32 2.6.1 (5.4.0 available)
#  xdg_directories 0.2.0+1 (1.0.4 available)
#  xml 6.1.0 (6.5.0 available)
#  yaml 3.1.1 (3.1.2 available)